In [6]:
import cv2
import numpy as np

a = cv2.imread("OCR.png", cv2.IMREAD_GRAYSCALE)

In [8]:
print(a)

[[240 240 240 ... 240 240 240]
 [240 240 240 ... 240 240 240]
 [240 240 240 ... 240 240 240]
 ...
 [240 240 240 ... 240 240 240]
 [240 240 240 ... 240 240 240]
 [240 240 240 ... 240 240 240]]


In [7]:
def bilinear_interpolate(gray_np_image, p00, p10, p01, p11):
    

SyntaxError: unexpected EOF while parsing (<ipython-input-7-a898cb305d69>, line 1)