In [18]:
import numpy as np

alpha = 0.5

X = np.array([[1, 1, 0], 
             [1, 2, -1], 
             [1, 4, 0], 
             [1, 2, 2], 
             [1, 3, 3]], dtype=np.float64)

Y = np.array([-1, -1, -1, 1, 1], dtype=np.float64)

w = np.array([-12, 2, 3], dtype=np.float64)

n = 4

for i in range(n):
    w -= alpha * np.dot((np.sign(np.dot(X, w)) - Y), X)
    print(w)

[-11.   4.   5.]
[-12.   0.   5.]
[-11.   2.   7.]
[-11.   2.   7.]
